In [19]:
import numpy
import open3d as o3d
from plyfile import PlyData, PlyElement
import numpy as np
import os

In [20]:
'''
plydata = PlyData.read('data\instances_control\inst_001.ply')
for i in range(0, plydata.elements[0].count):
    data[i] = [plydata['vertex']['x'][i], plydata['vertex']['y'][i], plydata['vertex']['z'][i]]
'''

"\nplydata = PlyData.read('data\\instances_control\\inst_001.ply')\nfor i in range(0, plydata.elements[0].count):\n    data[i] = [plydata['vertex']['x'][i], plydata['vertex']['y'][i], plydata['vertex']['z'][i]]\n"

In [47]:
directory = os.fsencode("data\instances_control")
counter = 0;
arr = []
# Read .ply file
for file in os.listdir(directory):
    
    input_file = directory + b"\\" + file
    pcd = o3d.io.read_point_cloud(input_file) # Read the point cloud
    counter += 1
    print(counter)
    # Visualize the point cloud within open3d
    # o3d.visualization.draw_geometries([pcd]) 

    # Convert open3d format to numpy array
    # Here, you have the point cloud in numpy format. 
    point_cloud_in_numpy = np.asarray(pcd.points) 
    arr.append(point_cloud_in_numpy)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100


In [48]:
display(arr)
point_cloud_in_numpy

[array([[-65.17018127,  17.93083572,   2.50840259],
        [-67.95219421,  20.13541794,  -4.00063086],
        [-72.75547791,  25.30211639, -27.51113892],
        ...,
        [ 37.66835022,   1.63555372,  28.52712822],
        [ 32.72903442,   1.35596061,  30.66774368],
        [-16.55862427,   2.75448155,  33.0082016 ]]),
 array([[-59.52382278,  13.28960991,   3.27208734],
        [-62.3783989 ,  15.18552876,  -1.73386991],
        [-67.01100922,  19.52219582, -20.27849197],
        ...,
        [ 34.35001755,   1.7152667 ,  25.12957001],
        [ 29.90026474,   1.05010092,  27.18575096],
        [-16.40753555,   0.36459294,  30.14697838]]),
 array([[-58.80090714,  17.51729965,   0.7808103 ],
        [-61.9947052 ,  19.33211136,  -4.55955267],
        [-69.47897339,  23.94570541, -25.04018402],
        ...,
        [ 34.22566986,   1.15635502,  25.15253639],
        [ 29.25209618,   0.24939263,  26.84857941],
        [-14.98480701,   1.65129042,  30.20291328]]),
 array([[-60.621051

array([[-58.78326797,  16.87905502,   4.74159479],
       [-61.38581467,  18.97066116,  -1.52967787],
       [-65.14794159,  23.46741676, -23.62330246],
       ...,
       [ 35.1618576 ,   3.02059531,  30.37468529],
       [ 30.74629784,   2.41421103,  32.99105072],
       [-16.77666664,   1.76428676,  35.4513588 ]])