# Import Libraries

In [20]:
import numpy
import open3d as o3d
from plyfile import PlyData, PlyElement
import numpy as np
import os
import pandas

# Preprocessing

## PlyData Preprocessing Test

In [20]:
'''
plydata = PlyData.read('data\instances_control\inst_001.ply')
for i in range(0, plydata.elements[0].count):
    data[i] = [plydata['vertex']['x'][i], plydata['vertex']['y'][i], plydata['vertex']['z'][i]]
'''

"\nplydata = PlyData.read('data\\instances_control\\inst_001.ply')\nfor i in range(0, plydata.elements[0].count):\n    data[i] = [plydata['vertex']['x'][i], plydata['vertex']['y'][i], plydata['vertex']['z'][i]]\n"

## Open3D Preprocessing Test

In [ ]:
# Read .ply file
input_file = "data\instances_control\inst_001.ply"
pcd = o3d.io.read_point_cloud(input_file) # read the point cloud

display(input_file)

# Visualize the point cloud within open3d
o3d.visualization.draw_geometries([pcd]) 

# convert open3d format to numpy array
# here, you have the point cloud in numpy format. 
point_cloud_in_numpy = np.asarray(pcd.points) 

'data\\instances_control\\inst_001.ply'

[Open3D WARNING] [ViewControl] SetViewPoint() failed because window height and width are not set.


## Open3D Preprocessing ~ Instances Control 

In [17]:
directory = os.fsencode("data\instances_control")
instance_control_arr = []
# Read .ply file
for file in os.listdir(directory):
    
    input_file = directory + b"\\" + file
    pcd = o3d.io.read_point_cloud(input_file) # read the point cloud

    # convert open3d format to numpy array
    # here, you have the point cloud in numpy format
    point_cloud_in_numpy = np.asarray(pcd.points) 
    
    # append all instances to array
    instance_control_arr.append(point_cloud_in_numpy)

In [18]:
# Test Instance Control array
display(instance_arr)

[array([[-60.47789383,  17.03791809,   3.6020503 ],
        [-62.58651733,  18.49642181,  -1.86345994],
        [-66.22724915,  22.28835106, -21.9406662 ],
        ...,
        [ 34.49959564,   4.95233202,  28.00296974],
        [ 30.02422523,   4.56412697,  29.75492096],
        [-15.36316395,   3.33630657,  30.64749146]]),
 array([[-61.6386528 ,  15.68609142,   3.6024549 ],
        [-63.80805588,  17.05150604,  -1.68798888],
        [-65.40748596,  20.74142075, -21.85798073],
        ...,
        [ 34.86697006,   4.33936977,  26.77480698],
        [ 30.12904739,   4.68784761,  30.25327492],
        [-16.04827499,   4.42805576,  31.61532784]]),
 array([[-58.17732239,  15.95020199,   4.10709476],
        [-60.1648407 ,  18.27082253,  -1.88927484],
        [-62.36695862,  22.31302071, -22.44350433],
        ...,
        [ 33.5569191 ,   3.63784456,  28.60744286],
        [ 29.26482582,   3.98047781,  29.8227005 ],
        [-15.99634457,   4.32679224,  31.65812874]]),
 array([[-57.613773

## Open3D Preprocessing ~ Instances Coronal

In [14]:
directory = os.fsencode("data\instances_coronal")
instance_coronal_arr = []
# Read .ply file
for file in os.listdir(directory):
    
    input_file = directory + b"\\" + file
    pcd = o3d.io.read_point_cloud(input_file) # read the point cloud

    # convert open3d format to numpy array
    # here, you have the point cloud in numpy format
    point_cloud_in_numpy = np.asarray(pcd.points) 
    
    # append all instances to array
    instance_coronal_arr.append(point_cloud_in_numpy)

In [16]:
# Test Instance Coronal array
display(instance_coronal_arr)

[array([[-60.47789383,  17.03791809,   3.6020503 ],
        [-62.58651733,  18.49642181,  -1.86345994],
        [-66.22724915,  22.28835106, -21.9406662 ],
        ...,
        [ 34.49959564,   4.95233202,  28.00296974],
        [ 30.02422523,   4.56412697,  29.75492096],
        [-15.36316395,   3.33630657,  30.64749146]]),
 array([[-61.6386528 ,  15.68609142,   3.6024549 ],
        [-63.80805588,  17.05150604,  -1.68798888],
        [-65.40748596,  20.74142075, -21.85798073],
        ...,
        [ 34.86697006,   4.33936977,  26.77480698],
        [ 30.12904739,   4.68784761,  30.25327492],
        [-16.04827499,   4.42805576,  31.61532784]]),
 array([[-58.17732239,  15.95020199,   4.10709476],
        [-60.1648407 ,  18.27082253,  -1.88927484],
        [-62.36695862,  22.31302071, -22.44350433],
        ...,
        [ 33.5569191 ,   3.63784456,  28.60744286],
        [ 29.26482582,   3.98047781,  29.8227005 ],
        [-15.99634457,   4.32679224,  31.65812874]]),
 array([[-57.613773

## Open3D Preprocessing ~ Instances Full

In [23]:
directory = os.fsencode("data\instances_full")
instance_full_arr = []
# Read .ply file
for file in os.listdir(directory):
    
    input_file = directory + b"\\" + file
    pcd = o3d.io.read_point_cloud(input_file) # read the point cloud

    # convert open3d format to numpy array
    # here, you have the point cloud in numpy format
    point_cloud_in_numpy = np.asarray(pcd.points) 
    
    # append all instances to array
    instance_full_arr.append(point_cloud_in_numpy)

In [24]:
# Test Instance Full array
display(instance_full_arr)

[array([[-54.24404907,  17.42485619,   3.79447365],
        [-55.63225174,  19.30572701,  -3.09423971],
        [-59.08646393,  24.33043671, -28.82621193],
        ...,
        [ 34.00392151,   1.76514614,  29.84215164],
        [ 29.58874702,   1.93247855,  30.98987389],
        [-16.33725739,   1.93493354,  31.80060577]]),
 array([[-56.85378647,  15.37411404,   6.94789791],
        [-58.73690033,  16.89904594,   1.60895669],
        [-62.47666931,  21.1213932 , -18.71567154],
        ...,
        [ 33.35011292,   3.69069386,  28.56628609],
        [ 28.86390877,   3.1625247 ,  31.16602325],
        [-15.73790073,   3.67566347,  34.68301773]]),
 array([[-52.51531219,  15.56710339,   4.66051531],
        [-54.96962357,  17.55347824,  -1.22252631],
        [-59.97903824,  21.74794006, -22.81044388],
        ...,
        [ 31.9240036 ,   2.16234446,  30.32593155],
        [ 27.49645042,   1.73308241,  31.888134  ],
        [-14.93395329,   3.29457402,  34.08153915]]),
 array([[-55.667209

## Open3D Preprocessing ~ Instances Metopic 

In [25]:
directory = os.fsencode("data\instances_metopic")
instance_metopic_arr = []
# Read .ply file
for file in os.listdir(directory):
    
    input_file = directory + b"\\" + file
    pcd = o3d.io.read_point_cloud(input_file) # read the point cloud

    # convert open3d format to numpy array
    # here, you have the point cloud in numpy format
    point_cloud_in_numpy = np.asarray(pcd.points) 
    
    # append all instances to array
    instance_metopic_arr.append(point_cloud_in_numpy)

In [26]:
# Test Instance Metopic array
display(instance_metopic_arr)

[array([[-60.92210388,  20.269907  ,   3.16388917],
        [-64.05847931,  22.27880287,  -3.28823566],
        [-71.01826477,  26.87614441, -25.74663734],
        ...,
        [ 35.21726608,   2.61852479,  30.19095612],
        [ 30.45575714,   1.66136205,  32.00270844],
        [-16.35638809,   2.76586342,  34.91448975]]),
 array([[-62.93683243,  18.06493759,   1.99667549],
        [-65.81925964,  20.25138283,  -4.02706242],
        [-71.91403198,  25.74619675, -26.83996201],
        ...,
        [ 35.73831177,   2.42512822,  28.44534302],
        [ 31.37180328,   1.26741719,  31.05930519],
        [-16.47117233,   2.31435752,  34.5116806 ]]),
 array([[-52.80955887,  16.86830902,   4.65859604],
        [-54.85559845,  18.70798683,  -1.94619501],
        [-58.9626236 ,  23.53004837, -25.26237106],
        ...,
        [ 31.88320351,   1.82748055,  31.79148102],
        [ 27.1780262 ,   0.92361552,  33.62545013],
        [-14.16225529,   2.59232855,  37.0365181 ]]),
 array([[-54.697315

## Open3D Preprocessing ~ Instances Sagittal

In [27]:
directory = os.fsencode("data\instances_sagittal")
instance_sagittal_arr = []
# Read .ply file
for file in os.listdir(directory):
    
    input_file = directory + b"\\" + file
    pcd = o3d.io.read_point_cloud(input_file) # read the point cloud

    # convert open3d format to numpy array
    # here, you have the point cloud in numpy format
    point_cloud_in_numpy = np.asarray(pcd.points) 
    
    # append all instances to array
    instance_sagittal_arr.append(point_cloud_in_numpy)

In [28]:
# Test Instance Sagittal array
display(instance_sagittal_arr)

[array([[-53.44871521,  17.16610146,   3.66192722],
        [-55.23622131,  19.10370064,  -2.93416953],
        [-60.41489792,  24.01064682, -26.96372032],
        ...,
        [ 32.16527176,   1.6884321 ,  30.87685585],
        [ 27.3503418 ,   1.64411926,  32.83338165],
        [-15.57067585,   2.01553726,  34.79740524]]),
 array([[-57.93574905,  17.20279694,   5.40786648],
        [-59.50196457,  19.2572155 ,  -1.14416683],
        [-63.92695618,  23.90646172, -23.92815208],
        ...,
        [ 34.27160263,   2.23629189,  28.88322449],
        [ 29.50483322,   2.18578649,  30.70896339],
        [-15.96513081,   1.88695776,  31.46426773]]),
 array([[-47.88620758,  15.33307266,   4.09131241],
        [-49.47562408,  17.32699585,  -2.51725674],
        [-53.61216354,  21.78982925, -26.10101891],
        ...,
        [ 29.24454308,  -0.21410367,  28.91409874],
        [ 24.70411491,  -0.15240356,  29.97716522],
        [-13.99878311,   0.10362448,  33.61132812]]),
 array([[-56.936046